
name: BiliBili每日任务
on:
  workflow_dispatch: # 允许手动运行
  schedule:
    - cron: '30 22 * * *' # 每天北京时间 06:30

jobs:
  run-bilibili-tool:
    runs-on: ubuntu-latest
steps:
      - name: 运行 BiliBiliTool Pro
        run: |
          docker run --rm \
          -e Ray_BiliBiliCookies__0="${{ secrets.COOKIE_STR }}" \
          -e Ray_RunTasks="Daily" \
          ghcr.io/raywangqvq/bilibili_tool_pro
